# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_person', models.CharField(max_length=128)),
                ('shipping_person', models.CharField(max_length=128)),
                ('shipping_tel', models.CharField(max_length=128)),
                ('shipping_address', models.CharField(max_length=128)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
