# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
