# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_auto_20181123_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='下单日期'),
        ),
    ]
